# Generated by Django 3.2.7 on 2021-09-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myidol', '0002_alter_clusterinfo_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
