# Generated by Django 3.2.7 on 2021-09-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myidol', '0003_alter_imageinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myidol.imageinfo', verbose_name='image_id')),
            ],
        ),
    ]
