# Generated by Django 3.2.7 on 2021-09-07 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myidol', '0004_embeddinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddinginfo',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0, size=128),
        ),
    ]
